language: python

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - conda config --set always_yes yes
  - conda create --quiet -n py37 python=3.7
  - source activate py37

# Install packages
install:
  - conda install --quiet pytorch=1.3.0 -c pytorch
  - conda install --quiet flake8

script:
  - flake8 .